# Generated by Django 5.0.1 on 2024-03-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
