# Generated by Django 5.0.1 on 2024-03-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_owner_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteacher',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.stream'),
        ),
    ]
